use rand::RngCore;
use serde::{Deserialize, Serialize};
use std::path::Path;

use super::ShareError;
use super::crypto::{decrypt_message, derive_package_key, encrypt_message};

/// A decrypted vault item ready for sharing. All sensitive fields are Option<String>
/// so that different item types can be represented without a separate enum.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct PlainItem {
    pub item_type: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

/// The on-disk format for an encrypted package file.
/// All binary fields are base64-encoded for JSON compatibility.
#[derive(Serialize, Deserialize)]
pub struct PackageFile {
    pub version: u8,
    /// Base64-encoded 32-byte Argon2 salt.
    pub salt: String,
    /// Base64-encoded nonce || AES-GCM ciphertext.
    pub ciphertext: String,
}

/// Payload encrypted inside the package file.
#[derive(Serialize, Deserialize)]
struct PackagePayload {
    items: Vec<PlainItem>,
    exported_at: u64,
}

/// Export a list of plain items to an encrypted `.vault` package file.
/// The passphrase is generated by the caller via `crypto::generate_passphrase`.
pub fn export_package(
    items: &[PlainItem],
    path: &Path,
    passphrase: &str,
) -> Result<(), ShareError> {
    // Generate random salt
    let mut salt = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut salt);

    let key = derive_package_key(passphrase, &salt);

    let exported_at = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let payload = PackagePayload {
        items: items.to_vec(),
        exported_at,
    };

    let payload_bytes =
        serde_json::to_vec(&payload).map_err(|e| ShareError::Protocol(e.to_string()))?;

    let ciphertext = encrypt_message(&key, &payload_bytes);

    let package = PackageFile {
        version: 1,
        salt: base64_encode(&salt),
        ciphertext: base64_encode(&ciphertext),
    };

    let json =
        serde_json::to_string_pretty(&package).map_err(|e| ShareError::Protocol(e.to_string()))?;

    std::fs::write(path, json).map_err(|e| ShareError::Io(e.to_string()))?;

    Ok(())
}

/// Import and decrypt a `.vault` package file.
/// Returns the list of plain items.
pub fn import_package(path: &Path, passphrase: &str) -> Result<Vec<PlainItem>, ShareError> {
    let json = std::fs::read_to_string(path).map_err(|e| ShareError::Io(e.to_string()))?;

    let package: PackageFile =
        serde_json::from_str(&json).map_err(|e| ShareError::Protocol(e.to_string()))?;

    if package.version != 1 {
        return Err(ShareError::Protocol(format!(
            "unsupported package version: {}",
            package.version
        )));
    }

    let salt_bytes = base64_decode(&package.salt)
        .map_err(|_| ShareError::Protocol("invalid salt encoding".into()))?;
    if salt_bytes.len() != 32 {
        return Err(ShareError::Protocol("salt must be 32 bytes".into()));
    }
    let salt: [u8; 32] = salt_bytes.try_into().expect("length already checked");

    let key = derive_package_key(passphrase, &salt);

    let ct_bytes = base64_decode(&package.ciphertext)
        .map_err(|_| ShareError::Protocol("invalid ciphertext encoding".into()))?;

    let plaintext = decrypt_message(&key, &ct_bytes)?;

    let payload: PackagePayload =
        serde_json::from_slice(&plaintext).map_err(|e| ShareError::Protocol(e.to_string()))?;

    Ok(payload.items)
}

// ─── Minimal base64 (no external dep beyond what's already here) ──────────────
// We implement a simple standard base64 to avoid adding the `base64` crate.

const BASE64_CHARS: &[u8] =
    b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

fn base64_encode(input: &[u8]) -> String {
    let mut out = String::new();
    let mut i = 0;
    while i < input.len() {
        let b0 = input[i] as u32;
        let b1 = if i + 1 < input.len() { input[i + 1] as u32 } else { 0 };
        let b2 = if i + 2 < input.len() { input[i + 2] as u32 } else { 0 };

        out.push(BASE64_CHARS[((b0 >> 2) & 0x3F) as usize] as char);
        out.push(BASE64_CHARS[(((b0 << 4) | (b1 >> 4)) & 0x3F) as usize] as char);

        if i + 1 < input.len() {
            out.push(BASE64_CHARS[(((b1 << 2) | (b2 >> 6)) & 0x3F) as usize] as char);
        } else {
            out.push('=');
        }
        if i + 2 < input.len() {
            out.push(BASE64_CHARS[(b2 & 0x3F) as usize] as char);
        } else {
            out.push('=');
        }
        i += 3;
    }
    out
}

fn base64_char_value(c: u8) -> Option<u8> {
    match c {
        b'A'..=b'Z' => Some(c - b'A'),
        b'a'..=b'z' => Some(c - b'a' + 26),
        b'0'..=b'9' => Some(c - b'0' + 52),
        b'+' => Some(62),
        b'/' => Some(63),
        b'=' => None, // padding
        _ => None,
    }
}

fn base64_decode(input: &str) -> Result<Vec<u8>, ()> {
    let input = input.trim();
    if input.len() % 4 != 0 {
        return Err(());
    }
    let mut out = Vec::with_capacity(input.len() / 4 * 3);
    let bytes = input.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let v0 = base64_char_value(bytes[i]).ok_or(())?;
        let v1 = base64_char_value(bytes[i + 1]).ok_or(())?;

        out.push((v0 << 2) | (v1 >> 4));

        if bytes[i + 2] != b'=' {
            let v2 = base64_char_value(bytes[i + 2]).ok_or(())?;
            out.push((v1 << 4) | (v2 >> 2));
            if bytes[i + 3] != b'=' {
                let v3 = base64_char_value(bytes[i + 3]).ok_or(())?;
                out.push((v2 << 6) | v3);
            }
        }
        i += 4;
    }
    Ok(out)
}
